### ISSUE TITLE
[Bug]: Old conversations cannot be loaded after upgrading to 1.21.0

### ISSUE THREAD

**Issue by eluinstra** [OpenHands/OpenHands#17615]
### Operating System

Linux

### Installation Method

npm (`npm install -g @openhands/agent-canvas`)

### Agent Canvas Version

1.21.0

### Bug Description

After upgrading to 1.21.0 when I want to open an old conversation the page keeps trying to reload with the error message `Unable to connect to server` with the following error message in the logging:

```
09:51:00 [agent-server] WARNING  Error closing agent: 'LocalConversation' object has no attribute 'agent'  local_conversation.py:2795
09:51:01 [agent-server] INFO     ::ffff:172.17.0.1:0 - "WebSocket /sockets/events/437f812d-3676-4e69-8c56-0e81297f9920?resend_mode=all" [accepted]  wsproto_impl.py:385
09:51:01 [agent-server] INFO     WebSocket authenticated via first-message auth  sockets.py:223
09:51:01 [agent-server] INFO     Event Websocket Connected: 437f812d-3676-4e69-8c56-0e81297f9920  sockets.py:283
09:51:01 [agent-server] ERROR    Exception in ASGI application
  wsproto_impl.py:366
09:51:01 [agent-server] WARNING  Error closing agent: 'LocalConversation' object has no attribute 'agent'  local_conversation.py:2795
09:51:02 [agent-server] INFO     ::ffff:172.17.0.1:0 - "WebSocket /sockets/events/437f812d-3676-4e69-8c56-0e81297f9920?resend_mode=all" [accepted]  wsproto_impl.py:385
09:51:02 [agent-server] INFO     WebSocket authenticated via first-message auth  sockets.py:223
09:51:02 [agent-server] INFO     Event Websocket Connected: 437f812d-3676-4e69-8c56-0e81297f9920  sockets.py:283
09:51:02 [agent-server] ERROR    Exception in ASGI application
  wsproto_impl.py:366
```

A new conversation works fine

### Steps to Reproduce

Update an existing agent-canvas installation with conversations to 1.21.0

### Actual Behavior

when opening an old conversation the page keeps trying to reload with the error message `Unable to connect to server`.

<img width="1894" height="1006" alt="Image" src="https://github.com/user-attachments/assets/08173998-4a0a-464c-8656-b1b6ab2c27b9" />

### Expected Behavior

when opening an old conversation, the conversation will show

### Relevant Logs

```shell
09:51:00 [agent-server] WARNING  Error closing agent: 'LocalConversation' object has no attribute 'agent'  local_conversation.py:2795
09:51:01 [agent-server] INFO     ::ffff:172.17.0.1:0 - "WebSocket /sockets/events/437f812d-3676-4e69-8c56-0e81297f9920?resend_mode=all" [accepted]  wsproto_impl.py:385
09:51:01 [agent-server] INFO     WebSocket authenticated via first-message auth  sockets.py:223
09:51:01 [agent-server] INFO     Event Websocket Connected: 437f812d-3676-4e69-8c56-0e81297f9920  sockets.py:283
09:51:01 [agent-server] ERROR    Exception in ASGI application
  wsproto_impl.py:366
09:51:01 [agent-server] WARNING  Error closing agent: 'LocalConversation' object has no attribute 'agent'  local_conversation.py:2795
09:51:02 [agent-server] INFO     ::ffff:172.17.0.1:0 - "WebSocket /sockets/events/437f812d-3676-4e69-8c56-0e81297f9920?resend_mode=all" [accepted]  wsproto_impl.py:385
09:51:02 [agent-server] INFO     WebSocket authenticated via first-message auth  sockets.py:223
09:51:02 [agent-server] INFO     Event Websocket Connected: 437f812d-3676-4e69-8c56-0e81297f9920  sockets.py:283
09:51:02 [agent-server] ERROR    Exception in ASGI application
  wsproto_impl.py:366
```

### Acceptance Criteria

- I want that after an upgrade to version 1.21.0 conversations from older versions can still be viewed.

**Comment by VascoSch92** [comment]
Thanks for the detailed report — I've reproduced this locally and it's a real regression in 1.21.0.

## Workaround: downgrade to 1.20.0

```
npm install -g @openhands/agent-canvas@1.20.0
```

Your conversations on disk are fine — nothing is corrupted and there's nothing to repair. It's the reader in 1.21.0 that's too strict, so a downgrade should make them open again.

Two caveats:

- 1.20.0 pins an agent-server that resolves `fastmcp` 4.x, which is exactly what the 1.21.0 dependency change was fixing. If you rely on the browser tools you may see problems there instead — it's a trade-off until we ship a proper fix.
- Any conversation you create while back on 1.20.0 will be written in the same format, so it'll break again when you next upgrade. We'll make the fix read both.

## What we think is happening (needs your confirmation)

1.21.0 pins `fastmcp<4`, which downgrades the transitive `mcp` package from 2.x to 1.x. Those two versions spell the MCP tool schema field differently (`input_schema` vs `inputSchema`), and 1.x refuses to read what 2.x wrote. So conversations that had an **MCP server attached**, created roughly between 2026-08-31 and 2026-09-17, fail to load — while conversations without MCP tools, and all new conversations, are fine.

That matches your symptoms exactly, but the `Exception in ASGI application` line in your log hides the actual exception, so I can't yet confirm yours is the same failure. The `Error closing agent: 'LocalConversation' object has no attribute 'agent'` warning is a separate masking bug — it's what's swallowing the real error, and we'll fix that too.

## Could you share the following?

1. **The full traceback.** The most useful single thing. The `Exception in ASGI application` entry has a full traceback under it that got cut from your paste — the last ~20 lines, especially anything mentioning `ValidationError`.

2. **Which version you upgraded from**, and roughly when you first installed Agent Canvas on that machine. The install date matters more than the version here.

3. **Do the affected conversations use MCP servers?** If yes, which ones (GitHub, etc.)? If you were *not* using MCP at all, our diagnosis is wrong and we'd want to know early.

4. **Does this hit every old conversation, or only some?** In our repro only 4 of 11 failed.

5. **The dependency versions your agent-server resolved:**

   ```
   uvx --from openhands-agent-server==1.49.3 python -c "import importlib.metadata as m; print('fastmcp', m.version('fastmcp'), 'mcp', m.version('mcp'))"
   ```

6. **Which of your conversations carry the suspect format.** Save this as `diag.py` and run `python3 diag.py` — it only reads, and prints conversation IDs, no message content:

   ```python
   import json, os, glob
   roots = glob.glob(os.path.expanduser("~/.openhands/agent-canvas/dev_conversations")) + \
           glob.glob(os.path.expanduser("~/.openhands/agent-canvas/conversations"))
   hits = []
   for root in roots:
       for conv in sorted(os.listdir(root)):
           ev = os.path.join(root, conv, "events")
           if not os.path.isdir(ev): continue
           for f in os.listdir(ev):
               if not f.endswith(".json"): continue
               try: j = json.load(open(os.path.join(ev, f)))
               except Exception: continue
               for t in j.get("tools") or []:
                   m = isinstance(t, dict) and t.get("mcp_tool")
                   if isinstance(m, dict) and "input_schema" in m:
                       hits.append(conv); break
               else: continue
               break
   print(f"affected conversations: {len(hits)}")
   for h in hits: print(" ", h)
   ```

   If the IDs it prints are the same ones that fail to open, that confirms the diagnosis. If it prints `0`, something else is going on.

**Comment by eluinstra** [comment]
> ## Could you share the following?
> 1. **The full traceback.** The most useful single thing. The `Exception in ASGI application` entry has a full traceback under it that got cut from your paste — the last ~20 lines, especially anything mentioning `ValidationError`.
> 2. **Which version you upgraded from**, and roughly when you first installed Agent Canvas on that machine. The install date matters more than the version here.
> 3. **Do the affected conversations use MCP servers?** If yes, which ones (GitHub, etc.)? If you were _not_ using MCP at all, our diagnosis is wrong and we'd want to know early.
> 4. **Does this hit every old conversation, or only some?** In our repro only 4 of 11 failed.
> 5. **The dependency versions your agent-server resolved:**
>    ```
>    uvx --from openhands-agent-server==1.49.3 python -c "import importlib.metadata as m; print('fastmcp', m.version('fastmcp'), 'mcp', m.version('mcp'))"
>    ```
> 6. **Which of your conversations carry the suspect format.** 

1. It does not log anymore then I put in the log report
2. 1.20.0
3. yes, like Filesystem
4. almost every conversation
5. fastmcp 3.4.7 mcp 1.30.0
6. I cannot provide you with that

**Comment by VascoSch92** [comment]
Thanks.

This should be fixed in the last release. 

Please let me know if you have problems.
